[package]
name = "comma"
description = "runs programs without installing them"
version = "1.4.1"
edition = "2021"
authors = ["Artturin <Artturin@artturin.com>"]
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.11", features = ["derive", "cargo", "env"] }
xdg = "2.4.1"
